version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    restart: always

  app:
    build:
      context: .
    volumes:
      - ./OrangeHRMPytest:/OrangeHRMPytest
    command: python3 -m pytest -v --html=./OrangeHRM.html
    depends_on:
      - selenium